markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables", "strikethrough"]
permalink: /:year/:month/:day/:title 
title: Tao Zhang
url: http://ztpala.com
githubEditBaseURL: https://github.com/pala/pala.github.com/edit/master/
subscribe: http://ztpala.com/atom.xml
exclude: [ README.md, newpost.rb ]
domain: ztpala.com
author: Tao Zhang
email: ztpala+blog@gmail.com
twitterID: ztpala
googleAnalyticsID: UA-5531632-1
disqusShortname: ztpala
timezone: America/New_York
